name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: node:14-alpine
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release 
